### ISSUE TITLE
MacOS build failures on master & develop

### ISSUE THREAD

**Issue by ojacobson** [webpack/webpack.io#54] opened 2016-07-26 03:13 UTC
OS: Mac OS 10.11.6 (Darwin Dashie.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64)

Node: v6.3.0 (via Homebrew)

Did:

```bash
$ git clean -fdx
$ git checkout master && git pull --ff-only
$ git rev-parse HEAD
7d59106a4dda6db7cce7c21ab4221f46a757936a
$ npm install --all
$ npm start
```

Expected: running development server on port 3000.

Actual result:

```
$ npm start

> webpack.io@0.0.0 start /Users/owen/Development/grimoire.ca/webpack.io
> antwar -d

(node:94709) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
2016.07.25.23.09.28 Start developing

module.js:442
    throw err;
    ^

Error: Cannot find module 'extract-text-webpack-plugin'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/owen/Development/grimoire.ca/webpack.io/webpack.config.js:2:25)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.3.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! webpack.io@0.0.0 start: `antwar -d`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack.io@0.0.0 start script 'antwar -d'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webpack.io package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     antwar -d
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webpack.io
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webpack.io
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/owen/Development/grimoire.ca/webpack.io/npm-debug.log
```

**Comment by TheLarkInn** [comment] 2016-07-26 03:50
Are you missing a dep from node modules? Something an `npm install` could fix?

**Comment by ojacobson** [comment] 2016-07-26 04:01
Manually installing `webpack-extract-text-plugin` changes the failure, so that's progress:

```
:( owen@Dashie:~/Development/grimoire.ca/webpack.io (master)
$ npm install extract-text-webpack-plugin
webpack.io@0.0.0 /Users/owen/Development/grimoire.ca/webpack.io
└─┬ extract-text-webpack-plugin@1.0.1
  ├── async@1.5.2
  └── webpack-sources@0.1.2

:) owen@Dashie:~/Development/grimoire.ca/webpack.io (master)
$ npm start

> webpack.io@0.0.0 start /Users/owen/Development/grimoire.ca/webpack.io
> antwar -d

(node:95206) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
2016.07.25.23.58.40 Start developing

2016.07.25.23.58.46
Developing failed
ERROR in ./antwar.config.js
Module not found: Error: Cannot resolve module 'json' in /Users/owen/Development/grimoire.ca/webpack.io
 @ ./antwar.config.js 44:15-48:9

ERROR in ./antwar.config.js
Module not found: Error: Cannot resolve module 'json' in /Users/owen/Development/grimoire.ca/webpack.io
 @ ./antwar.config.js 54:15-58:9

ERROR in ./antwar.config.js
Module not found: Error: Cannot resolve module 'json' in /Users/owen/Development/grimoire.ca/webpack.io
 @ ./antwar.config.js 64:15-68:9

ERROR in ./antwar.config.js
Module not found: Error: Cannot resolve module 'json' in /Users/owen/Development/grimoire.ca/webpack.io
 @ ./antwar.config.js 74:15-78:9
2016.07.25.23.58.46
Time elapsed: 5 seconds
```

Adding `npm install json` to the mix does allow `npm start` to actually start the dev server. It looks a bit crap, though - see attached screenshot. (Also, all the links point to `https://webpack.github.io/webpack.io/…path…`, rather than to resources served by the local server.)

![screen shot 2016-07-26 at 12 00 53 am](https://cloud.githubusercontent.com/assets/160985/17125739/242cf7e0-52c4-11e6-9e44-ce5c71f96351.png)

**Comment by bebraw** [comment] 2016-07-26 04:53
I can't repro this on `develop` (did a fresh install of deps). Node v5.11.1, npm 3.8.6.

I synced `master` with `develop` so they should be up to date now.

Can someone else confirm the issue?

**Comment by gregvenech** [comment] 2016-07-26 12:03
So on develop I added those missing deps to the package.json (extract-text... and the json-loader) however the `module.js:442` is the same one I've been seeing if I have the repo on my desktop or nested anywhere within. 

Somehow moving it to my user folder allows the scripts to run fine. I still haven't been able to figure out the cause of those failures, I'll try again tonight.

**Comment by gregvenech** [comment] 2016-07-30 02:34
@ojacobson I was able to start the [develop branch](https://github.com/webpack/webpack.io/tree/develop) above my desktop finally yesterday with no issue. I'm running a fairly similar environment, Mac OS 10.11.5 with Node 6.2.2.

Have you tried pulling a fresh copy of the branch and rerunning the scripts?

**Comment by gregvenech** [comment] 2016-08-10 02:56
Closing this issue as I am no longer able to replicate it. If anyone sees a similar issue, feel free to reopen with details...

**Comment by ojacobson** [comment] 2016-08-12 02:51
Hi! Sorry about the delay, I've been travelling.

I'm still able to reproduce it (or, if you prefer, unable to run the docs server locally) as of a clean copy of 7616b73bbfeffc518496c0b47830fa36f244db66, commit dated yesterday.

I've preserved my source tree in case I can be of any assistance.

**Comment by gregvenech** [comment] 2016-08-22 17:18
Hey @ojacobson no worries... I'm re-opening, are you seeing the same errors as before?

**Comment by ojacobson** [comment] 2016-08-26 01:45
Yeah, it's the same apparently-incorrect behaviour. The latest transcript is below, and produces this when browsed under `npm start`: 
![screen shot 2016-08-25 at 9 43 45 pm](https://cloud.githubusercontent.com/assets/160985/17991484/0b5e0568-6b0d-11e6-9b9f-bf5e59cd9458.png)

Commit:

```
$ git log -1
commit 5a2e228d657681624c04a4bae4586cc96fd8b4ea
Author: Greg Venech <greg.venech@gmail.com>
Date:   Wed Aug 24 09:01:41 2016 -0400

    Use Ubuntu Mono for code blocks
```

NPM installation from `git clean -fdx`:

```
$ npm install
npm WARN deprecated prism-languages@0.3.1: Use require('prismjs').languages instead
npm WARN deprecated promise.prototype.finally@1.0.1: Please upgrade to v2.0 or higher!
npm WARN deprecated graceful-fs@2.0.1: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated wrench@1.5.1: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> fsevents@1.0.14 install /Users/owen/Development/grimoire.ca/webpack.io/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/owen/Development/grimoire.ca/webpack.io/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" is installed via remote

> node-sass@3.8.0 install /Users/owen/Development/grimoire.ca/webpack.io/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/owen/Development/grimoire.ca/webpack.io/node_modules/node-sass/vendor/darwin-x64-48/binding.node

> node-sass@3.8.0 postinstall /Users/owen/Development/grimoire.ca/webpack.io/node_modules/node-sass
> node scripts/build.js

"/Users/owen/Development/grimoire.ca/webpack.io/node_modules/node-sass/vendor/darwin-x64-48/binding.node" exists.
 testing binary.
Binary is fine; exiting.
webpack.io@0.0.0 /Users/owen/Development/grimoire.ca/webpack.io
[dependency tree omitted]
npm WARN In antwar@0.7.3 replacing bundled version of history with history@3.0.0
```

Output of `npm start`:

```
$ npm start

> webpack.io@0.0.0 start /Users/owen/Development/grimoire.ca/webpack.io
> antwar -d

2016.08.25.21.43.23 Start developing

Failed to highlight javascriptis
module.exports = [ serverConfig, clientConfig ];

var serverConfig = {
  target: 'node',
  output: {
    path: 'dist',
    filename: 'lib.node.js'
  }
  //...
}

var clientConfig = {
  target: 'web' // <=== can be omitted as default is 'web'
  output: {
    path: 'dist'
    filename: 'lib.js'
  }
  //...
} TypeError: Cannot read property 'rest' of undefined
    at Object._self.Prism.tokenize (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:26368:22)
    at _self.Prism.highlight (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:26359:19)
    at Object.module.exports [as highlight] (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:42691:13)
    at Renderer.code (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:25580:29)
    at Parser.tok (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:25804:29)
    at Parser.parse (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:25749:18)
    at Function.Parser.parse [as parser] (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:25736:18)
    at Object.process (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:42757:22)
    at content (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:3149:26)
    at /Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:27738:16
Failed to highlight javascriptis
module.exports = [ serverConfig, clientConfig ];

var serverConfig = {
  target: 'node',
  output: {
    path: 'dist',
    filename: 'lib.node.js'
  }
  //...
}

var clientConfig = {
  target: 'web' // <=== can be omitted as default is 'web'
  output: {
    path: 'dist'
    filename: 'lib.js'
  }
  //...
} TypeError: Cannot read property 'rest' of undefined
    at Object._self.Prism.tokenize (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:26368:22)
    at _self.Prism.highlight (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:26359:19)
    at Object.module.exports [as highlight] (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:42691:13)
    at Renderer.code (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:25580:29)
    at Parser.tok (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:25804:29)
    at Parser.parse (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:25749:18)
    at Function.Parser.parse [as parser] (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:25736:18)
    at Object.process (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:42757:22)
    at content (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:3149:26)
    at /Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:27738:16
Failed to highlight javascriptis
module.exports = [ serverConfig, clientConfig ];

var serverConfig = {
  target: 'node',
  output: {
    path: 'dist',
    filename: 'lib.node.js'
  }
  //...
}

var clientConfig = {
  target: 'web' // <=== can be omitted as default is 'web'
  output: {
    path: 'dist'
    filename: 'lib.js'
  }
  //...
} TypeError: Cannot read property 'rest' of undefined
    at Object._self.Prism.tokenize (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:26368:22)
    at _self.Prism.highlight (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:26359:19)
    at Object.module.exports [as highlight] (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:42691:13)
    at Renderer.code (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:25580:29)
    at Parser.tok (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:25804:29)
    at Parser.parse (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:25749:18)
    at Function.Parser.parse [as parser] (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:25736:18)
    at Object.process (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:42757:22)
    at content (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:3149:26)
    at /Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:27738:16
Failed to highlight javascriptis
module.exports = [ serverConfig, clientConfig ];

var serverConfig = {
  target: 'node',
  output: {
    path: 'dist',
    filename: 'lib.node.js'
  }
  //...
}

var clientConfig = {
  target: 'web' // <=== can be omitted as default is 'web'
  output: {
    path: 'dist'
    filename: 'lib.js'
  }
  //...
} TypeError: Cannot read property 'rest' of undefined
    at Object._self.Prism.tokenize (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:26368:22)
    at _self.Prism.highlight (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:26359:19)
    at Object.module.exports [as highlight] (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:42691:13)
    at Renderer.code (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:25580:29)
    at Parser.tok (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:25804:29)
    at Parser.parse (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:25749:18)
    at Function.Parser.parse [as parser] (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:25736:18)
    at Object.process (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:42757:22)
    at content (/Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:3149:26)
    at /Users/owen/Development/grimoire.ca/webpack.io/.antwar/build/bundleStaticPage.js:27738:16
2016.08.25.21.43.30
Developing finished
2016.08.25.21.43.30
Time elapsed: 6 seconds
2016.08.25.21.43.30 Listening at port 3000

webpack: bundle is now VALID.
```

**Comment by gregvenech** [comment] 2016-08-26 02:27
I'm seeing the `Failed to highlight...` errors as well however I still see the site come up fine:

<img width="1440" alt="screen shot 2016-08-25 at 10 15 35 pm" src="https://cloud.githubusercontent.com/assets/8988697/17991993/80536292-6b11-11e6-9330-9e026d7fbed7.png">

I see a flash of un-styled content for about a second or two at most and then it the CSS loads and everything looks fine. I've actually been meaning to ask @bebraw about this as well as I figure it's something going on with antwar's customized webpack-dev-server. I see the `[HMR] Waiting for update signal from WDS...` in the console and it takes a lot longer than I'm used to with my other Webpack projects for everything else to load and to finally see the `[WDS] Hot Module Replacement enabled.` message come up.

I was more concerned that you were still hitting the missing dependencies or other build errors. @ojacobson what do you see in the browser console? I've never seen the un-styled content continue for more than a few seconds.

**Comment by ojacobson** [comment] 2016-08-26 03:01
Browser console output, `All` category, Safari Version 9.1.2 (11601.7.7):

```
[Error] Viewport argument key "minimal-ui" not recognized and ignored. (localhost, line 1)
[Log] [HMR] Waiting for update signal from WDS...
[Error] SyntaxError: Unexpected token '>'
	eval (main-bundle.js:1240)
	(anonymous function) (main-bundle.js:1240)
	__webpack_require__ (main-bundle.js:556)
	fn (main-bundle.js:87)
	eval code
	eval
	(anonymous function) (main-bundle.js:1924)
	__webpack_require__ (main-bundle.js:556)
	fn (main-bundle.js:87)
	eval code
	eval
	(anonymous function) (main-bundle.js:1936)
	__webpack_require__ (main-bundle.js:556)
	fn (main-bundle.js:87)
	eval code
	eval
	(anonymous function) (main-bundle.js:1858)
	__webpack_require__ (main-bundle.js:556)
	fn (main-bundle.js:87)
	eval code
	eval
	(anonymous function) (main-bundle.js:586)
	__webpack_require__ (main-bundle.js:556)
	(anonymous function) (main-bundle.js:579)
	global code (main-bundle.js:580)
[Log] [WDS] Hot Module Replacement enabled.
```

**Comment by gregvenech** [comment] 2016-08-26 03:23
Ah that seems to be what's going wrong. Btw just pushed 838c5bb70865aacabd308e7e5870281fd8bd7a54 which should fix the build, `Failed to highlight...`, errors. Let me see if I can reproduce what you're seeing with safari, and you might try using chrome or firefox in the meantime.

**Comment by ojacobson** [comment] 2016-08-26 03:33
Chrome works (with the same FOUC you're seeing), so I'll assume Firefox does, as well. I'm actually glad it's browser-dependent!

**Comment by gregvenech** [comment] 2016-08-26 03:34
Confirmed your issue with Safari, same error. Moving to #76 and closing this one. Tested in the latest versions of FF and Chrome which both seem to work fine.

**Comment by TheLarkInn** [comment] 2016-08-26 03:35
Is everyone using node v6 atleast, if not I would recommend trying it

**Closed by gregvenech** 2016-08-26 03:34 UTC

**Comment by gregvenech** [comment] 2016-08-26 03:35
@TheLarkInn yea we're both on 6.2+

**Comment by ojacobson** [comment] 2016-08-26 03:35
I am (v6.3.0 as of my last `brew update`).

**Comment by gregvenech** [comment] 2016-08-26 03:41
I'm on 6.2.2, originally we had thought being on 6+ was what was causing these things but it turned out to be a variety of other stuff (i.e. missing deps, browser issues, etc.) At least we finally got most of it nailed down.

**Comment by bebraw** [comment] 2016-08-26 05:15
By the looks of it, this was something Safari related. The problem is that it doesn't support ES6 features that well. I rewrote the offending bits in ES5 so you could try again after `npm update`.

We didn't notice this earlier as we were testing using the wrong browser.
